### ISSUE TITLE
Can I save the output .apk?

### ISSUE THREAD

**Issue by usernein** [oxr463/setup-cordova#1]
Is it possible to save the built apk? I want to use it as action artifact in my github action.

**Comment by oxr463** [comment]
Of course! You can use [fnkr/github-action-ghr](https://github.com/fnkr/github-action-ghr) for that.

Here is an example:

```yaml
- name: Publish GitHub Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: app/app-debug.apk
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by usernein** [comment]
Thank you for the link, it's really useful, but cordova runs in a Docker, right? So the platforms/ folder cannot be easily accessed by other steps like 'actions/upload-artifact' and that's what i was asking for: a way to get the built .apk

I did it by executing the commands in Dockerfile, without using setup-cordova:
https://github.com/deadlyjack/code-editor/blob/8084bf769aca918c1f330b20fe725fcf9069100a/.github/workflows/main.yml

**Comment by oxr463** [comment]
You will need to copy it into the top-level directory from the `platforms/android/app/build/outputs` directory, as part of your `cordova_exec` command.

```yml
with:
    exec: |
      cordova build --no-telemetry && \
      cp "$(find . -name '*.apk') .
```

Example: https://github.com/oxr463/pentesting-guide/blob/master/.github/workflows/main.yml#L16
