### ISSUE TITLE
Current working directory is not a Cordova-based project

### ISSUE THREAD

**Issue by mrtnpwn** [oxr463/setup-cordova#2]
While trying to setup this Action I got the following error:

```
... large docker command ...
5: Current working directory is not a Cordova-based project.
```

This is the yml file

```yaml
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build APK
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: cordova platform add android && \
                cordova build --no-telemetry && \
                cp "$(find . -name '*.apk')" .
```

and my file structure looks like this

```text
.
├── config.xml
├── hooks
│   └── cordova.js
├── package.json
├── package-lock.json
└── src
    ├── App.js
    ├── index.css
    ├── index.html
    └── index.js
```

Which was generated by the Cordova CLI utility.
